services:
  - type: web
    name: fundilink-api
    runtime: node
    repo: https://github.com/Wanderajonah/fundilinkug
    branch: master
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: COMMS_USERNAME
        sync: false
      - key: COMMS_API_KEY
        sync: false
      - key: COMMS_SENDER_ID
        sync: false
